config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get "/about" => "topics#about"

  resources :topics do
    resources :comments
  end

  resources :users

  root 'topics#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :categoryships, :dependent => :destroy
  has_many :topics, :through => :categoryships

  validates_presence_of :name

end

app/models/categoryship.rb
class Categoryship < ActiveRecord::Base

  belongs_to :topic
  belongs_to :category

  validates_presence_of :topic
  validates_presence_of :category


end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :topic, :counter_cache => true

  validates_presence_of :content

  def title
    self.topic.title
  end

  def can_delete_by?(user)
    ( self.user == user ) || ( self.topic.try(:user) == user ) || user.admin?
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base

  belongs_to :user

  has_many :comments, :dependent => :destroy

  has_many :categoryships, :dependent => :destroy
  has_many :categories, :through => :categoryships

  validates_presence_of :title

  def authors
    arr = [self.user]
    arr = arr +  self.comments.map{ |c| c.user }
    arr.compact
  end

  def can_delete_by?(user)
    (self.user == user ) || user.admin?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :topics
  has_many :comments

  def display_name
    self.username
  end

  def set_admin!
    self.role = "admin"
    self.save!
  end

  def admin?
    self.role == "admin"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << :username
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.build( comment_params )
    @comment.user = current_user

    if @comment.save
      redirect_to topic_path(@topic)
    else
      render "/topics/show"
    end
  end

  def destroy
    @topic = Topic.find( params[:topic_id] )
    @comment = @topic.comments.find( params[:id] )

    if comment.can_delete_by?(current_user)
      @comment.destroy
    end

    redirect_to :back
  end

  protected

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :authenticate_user!

  def index
    if params[:cid]
      category = Category.find( params[:cid] )
      @topics = category.topics
    else
      @topics = Topic.all
    end

    @q = @topics.search(params[:q])
    @topics = @q.result(distinct: true)

    @topics = @topics.page(params[:page]).per(15)
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user

    if @topic.save
      redirect_to topics_url
    else
      render :action => :new
    end
  end


  def destroy
    @topic = Topic.find( params[:id] )

    if @topic.can_delete_by?(current_user)
      @topic.destroy
    end

    redirect_to topics_url
  end

  def about
  end

  protected

  def topic_params
    params.require(:topic).permit(:title, :content, :category_ids => [])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
    @user = User.find( params[:id] )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForumExercise</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


      <% if current_user %>
          <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
          <%= link_to('修改密碼', edit_registration_path(:user)) %>
      <% else %>
          <%= link_to('註冊', new_registration_path(:user)) %> |
          <%= link_to('登入', new_session_path(:user)) %>
      <% end %>

<%= link_to "New Topic", new_topic_path %>
<%= link_to "About", about_path %>


<%= yield %>

</body>
</html>

app/views/topics/about.html.erb
<h2>About</h2>

<p>Total topic: <%= Topic.count %></p>
<p>Total comments: <%= Comment.count %></p>
<p>Total users: <%= User.count %></p>

app/views/topics/index.html.erb
<h2>Topic List</h2>

<%= sort_link(@q, :created_at, 'Created At', default_order: :desc) %> |
<%= sort_link(@q, :comments_count, 'Comments', default_order: :desc) %>

<% Category.all.each do |c| %>
  <%= link_to c.name, topics_path( :cid => c.id ) %>
<% end %>
<%= link_to "All", topics_path %>

<table>
  <tr>
    <th>Topic</th>
    <th>Category</th>
    <th>Authors</th>
    <th>Comments</th>
    <th>Time</th>
  </tr>

  <% @topics.each do |t| %>
    <tr>
      <td><%= link_to t.title, topic_path(t) %></td>
      <td><%= t.categories.map{ |c| c.name }.join(", ") %></td>
      <td>
        <% t.authors.each do |a| %>
          <%= link_to a.display_name, user_path(a) %>
        <% end %>
      </td>
      <td><%= t.comments_count %></td>
      <td><%= t.created_at.strftime("%B %d at %I:%M %p") %></td>
    </tr>
  <% end %>

</table>

<%= paginate @topics %>

app/views/topics/new.html.erb
<%= form_for @topic do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.submit "Submit" %>

<% end %>

app/views/topics/show.html.erb
<h2><%= @topic.title %></h2>

<p><%= @topic.content %></p>

<p><%= @topic.user.try(:display_name) %></p>

<% if @topic.can_delete_by?(current_user) %>
  <p><%= link_to "Delete Topic", topic_path(@topic), :method => :delete %>
<% end %>

<h2>Comments</h2>

<% @topic.comments.each do |comment| %>

  <p><%= comment.content %> by <%= comment.user.try(:display_name) %>

  <% if comment.can_delete_by?(current_user) %>
   <%= link_to "(Delete)", topic_comment_path(@topic, comment), :method => :delete %>
  <% end %>

  </p>

<% end %>


<h2>New comment</h2>

<%= form_for Comment.new, :url => topic_comments_path(@topic) do |f| %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit "Reply" %>

<% end %>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>

<h2>Topics</h2>

<ul>
<% @user.topics.each do |t| %>
  <li><%= link_to t.title, topic_path(t) %></li>
<% end %>
</ul>

<h2>Comments</h2>

<% @user.comments.each do |c| %>
  <li><%= link_to truncate(c.content), topic_path(c.topic) %></li>
<% end %>
</ul>